services:
  - type: web
    name: agridoc-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && pip install --upgrade setuptools gunicorn google-genai
    startCommand: cd AgriDoc/main_app && gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src/AgriDoc/main_app
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHON_VERSION
        value: 3.9.0

